name: Python Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-xvfb
        
    - name: Install Xvfb (Linux only)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        
    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: |
        xvfb-run python -m pytest tests/ -v
        
    - name: Run tests (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pytest tests/ -v