name: Python Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-xvfb
        
    - name: Run tests
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install xvfb
          xvfb-run python -m pytest tests/ -v
        else
          python -m pytest tests/ -v
        fi