name: Python Tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 5  # Hard timeout limit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        
    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: |
        python -m pytest tests/ -v --durations=5
        
    - name: Run tests (Windows)
      if: runner.os == 'Windows'
      run: |
        python -m pytest tests/ -v --durations=5